# Generated by Django 5.2.8 on 2025-11-21 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('student_id', models.CharField(max_length=50)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('gown_option', models.CharField(blank=True, help_text='Hire or Purchase from form', max_length=50)),
                ('additional_guests', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('gown_size', models.CharField(blank=True, max_length=20)),
                ('submission_id', models.CharField(blank=True, max_length=50)),
                ('attended', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.CharField(blank=True, max_length=100)),
                ('gown_collected', models.BooleanField(default=False)),
                ('gown_returned', models.BooleanField(default=False)),
                ('gown_notes', models.TextField(blank=True)),
                ('seat_row', models.CharField(blank=True, max_length=10)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('presentation_order', models.PositiveIntegerField(blank=True, help_text='Order for stage presentation', null=True)),
                ('display_name', models.CharField(blank=True, help_text='Name as shown on the big screen', max_length=255)),
                ('course_name', models.CharField(blank=True, help_text='Optional – course/qualification to display', max_length=255)),
            ],
            options={
                'ordering': ['presentation_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_graduate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_stage_state', to='ceremony.graduate')),
            ],
        ),
    ]
