# Generated by Django 5.2.8 on 2025-11-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
