# Generated by Django 5.2.8 on 2025-11-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremony', '0002_graduate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='gown_size',
            field=models.CharField(blank=True, choices=[('S(150- 160CM)', 'S'), ('M(160-170CM)', 'M'), ('L(170-180CM)', 'L')], max_length=20),
        ),
    ]
