# Generated by Django 5.2.8 on 2025-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremony', '0003_alter_graduate_gown_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='gown_size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
