# Generated by Django 5.2.8 on 2025-11-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremony', '0004_alter_graduate_gown_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
